#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# @file: data_analysis.py

from __future__ import division
import sys

import ngram
import nltk
import string
from config import *

pjoin = os.path.join


def count():
    """
    Results:

    train: 11701890
    existed: 355
    dev: 1000
    existed ratio: 0.355
    """
    fileName = train_click_log
    """fileName = '/home/lql/python/input.txt'"""
    with open(train_click_log, 'r') as f:
        for line in f:
            arr = line.strip().split('\t')
            image = arr[0].strip()
            query = arr[1].strip()
            click = string.atol(arr[2].strip())
            print image
            print query
            print click
if __name__ == "__main__":
    # query_existed()
    # query_search_test()
    count()
