#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# @file: data_analysis.py

from __future__ import division
import sys

import ngram
import nltk
import string
import sqlite3
from config import *

pjoin = os.path.join


def count():
    """
    Results:

    train: 11701890
    existed: 355
    dev: 1000
    existed ratio: 0.355
    """
    max_len = 0;
    fileName = train_click_log
    """fileName = '/home/lql/python/input.txt'"""
    with open(train_click_log, 'r') as f:
        for line in f:
            arr = line.strip().split('\t')
            query = arr[1].strip()
            l = len(query)
            if l > max_len:
                max_len = l
    print max_len

def make_qitable():
    print 'make qitable'
    qit = '../database/query_image_table.db3'
    con = sqlite3.connect(qit)
    cur = con.cursor()
    cur.execute('CREATE TABLE qit(query TEXT, image TEXT, click INTEGER)')
    con.commit()
    fileName = train_click_log
    with open(fileName, 'r') as f:
        for line in f:
            arr = line.strip().split('\t')
            image = '"%s"' % arr[0].strip()
            #'"%s, %s"' % (1, 2)
            #image = '"' + arr[0].strip() + '"'
            query = '"%s"' % arr[1].replace('"', '')
            click = arr[2].strip()
            cmd = 'INSERT INTO qit(query, image, click) VALUES(%s,%s,%s)' %(query,image,click)
            #print cmd
            cur.execute(cmd)
    con.commit()

def test_qitable():
    print 'test qitable'
    qit = '../database/query_image_table.db3'
    con = sqlite3.connect(qit)
    cur = con.cursor()
    query = '"black history month"'
    cmd = 'select * from qit where query=%s' %query
    cur.execute(cmd)
    con.commit()
    print cur.fetchall()

if __name__ == "__main__":
    # query_existed()
    # query_search_test()
    test_qitable()
